package com.brm.ws.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-05T13:13:55.264+09:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://payment.ws.brm.com/", name = "PaymentPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentPortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "transferFunds", targetNamespace = "http://payment.ws.brm.com/", className = "com.brm.ws.payment.TransferFunds")
    @WebMethod
    @ResponseWrapper(localName = "transferFundsResponse", targetNamespace = "http://payment.ws.brm.com/", className = "com.brm.ws.payment.TransferFundsResponse")
    public com.brm.ws.payment.TransferResponse transferFunds(
        @WebParam(name = "arg0", targetNamespace = "")
        com.brm.ws.payment.TransferRequest arg0
    ) throws TransferException_Exception;
}
